[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.6.0"

structopt = "0.3.25"

tracing = "0.1.29"
tracing-subscriber = { version = "0.3.6", features = ["env-filter", "std"] }

thiserror = "1.0.30"

common = { path = "../common" }
