[workspace]
members = [
    "client",
    "server",
    "common",
    # "ladder",
    # "matchmaker"
]

resolver = "2"

[patch.crates-io]
bevy = { path = "../bevy" }
# bevy = { git = "https://github.com/DJMcNab/bevy.git", branch = "breaker-of-bundles" }