[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.6.0", default-features = false }

tracing-subscriber = { version = "0.3.6", features = ["env-filter", "std"] }

common = { path = "../common" }
