[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.5"

heron = { version = "0.12.1", features = ["2d"] }

tracing = "0.1.29"
tracing-subscriber = { version = "0.3.2", features = ["env-filter", "std"] }

thiserror = "1.0.30"
